# tmp(!) alacritty config

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "ExtraLight"
size = 13.0

[window]
opacity = 0.7
startup_mode = "Maximized"
decorations = "None"
dynamic_padding = true
dimensions = { columns = 0, lines = 0 }

[scrolling]
history = 100000

[cursor]
style = { shape = "Block", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = false

# tokyo-night-enhanced
[colors]
footer_bar = { foreground = "#787c99", background = "#08080b" }

[colors.primary]
background = "#08080b"
foreground = "#787c99"

[colors.cursor]
cursor = "#787c99"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"
